name: "CI/CD Pipeline for a Node.js Application"

on:
 push:
  branches:
   - main
   
jobs:
 test_job:
  name: "job_1: test_job"
  runs-on: ubuntu-latest #ubuntu-latest self-hosted-windows
  steps:
   - name : "check out code"
     uses: actions/checkout@v3
     
   - name: "install node js 22"
     uses: actions/setup-node@v4
     with:
      node-version: '22'
   
   - name: "node dependency Install"
     run: npm install
   
   - name: "run test and store result"
     run: npm run check > test_result.txt
      
   - name: "upload test result in artifact"
     uses: actions/upload-artifact@v4
     with:
      name: test_result
      path: test_result.txt
     
 deploy_job:
  name: "job_2: deploy_job"
  runs-on: self-hosted-windows
  needs: test_job
  steps:
   - name: Download artifact
     uses: actions/download-artifact@v4
     with:
       name: test_result

   - name: "show test result"
     run: type test_result.txt

   - name : "check out code"
     uses: actions/checkout@v3
  
   - name: "node dependency Install"
     run: npm install
     
   - name: Install pm2 globally
     shell: bash
     run: npm install -g pm2
     
#   - name: "delete existing app and start new"
#     shell: powershell
#     run: |
#      npm install -g pm2;
#      $npmGlobalPrefix = npm config get prefix;
#      $env:PATH = "$npmGlobalPrefix;$npmGlobalPrefix\node_modules\pm2\bin;" + $env:PATH;
#      pm2 delete node-app -s -ErrorAction SilentlyContinue;
#      pm2 start "./src/server.js" --name node-app;
#      pm2 save;
#   - name: Install PM2 globally
#     run: npm install -g pm2
#
#   - name: Start app with PM2
#     run: pm2 start src/server.js --name my-node-app

   - name: Delete existing PM2 app if it exists
     shell: powershell
     run: |
          try {
            pm2 delete node-app
          } catch {
            Write-Host "PM2 app 'node-app' not found or already stopped. Continuing..."
          }

   - name: Start new PM2 app
     shell: powershell
     run: |
          pm2 start app.js --name "node-app"

   












      