name: "CI/CD Pipeline for a Node.js Application"

on:
 push:
  branches:
   - main
   
jobs:
 test_job:
  name: "job_1: test_job"
  runs-on: ubuntu-latest #ubuntu-latest self-hosted-windows
  steps:
   - name : "check out code"
     uses: actions/checkout@v3
     
   - name: "install node js 22"
     uses: actions/setup-node@v4
     with:
      node-version: '22'
   
   - name: "node dependency Install"
     run: npm install
   
   - name: "run test and store result"
     run: npm run check > test_result.txt
      
   - name: "upload test result in artifact"
     uses: actions/upload-artifact@v4
     with:
      name: test_result
      path: test_result.txt
      


     
 deploy_job:
  name: "job_2: deploy_job"
  runs-on: self-hosted-windows
  needs: test_job
  steps:
   - name: Download artifact
     uses: actions/download-artifact@v4
     with:
       name: test_result

   - name: "show test result"
     run: type test_result.txt

#   - name : "check out code"
#     uses: actions/checkout@v3
#     
#   - name: "install node js 22"
#     uses: actions/setup-node@v4
#     with:
#      node-version: '22'
#   
#   - name: "node dependency Install"
#     run: npm install
#     
#   - name: "start project"
#     run: npm start

   












      