name: "CI-CD for node js app"

on:
 push:
  branches:
   - main
   
jobs:
 test_job:
  name: "job_1: test_job"
  runs-on: ubuntu-latest
  steps:
   - name : "check out code"
     uses: actions/checkout@v3
     
   - name: Setup Node.js 22.x
     uses: actions/setup-node@v4 # Use the setup-node action
     with:
     node-version: '22.x'
     
   - name: "Node dependency Install"
     run: npm install
     
   - name: "Run test & store log"
     run: |
      mkdir -p test-results
      npm check > test-results/results.txt || echo "Test failed"
      
   - name: "Upload test result in artifact"
     uses: actions/upload-artifact@v3
     with:
      name: test-results
      path: test-results/results.txt
     
 deploy_job:
  name: "job_2: deploy_job"
  runs-on: ubuntu-latest
  needs: test_job
  steps:
   - name : "check out code"
     uses: actions/checkout@v3
     
   - name: "Download artifact"
     uses: actions/upload-artifact@v3
     with:
      name: test-results
      path: test-results/results.txt














      